version: '3.8'
services:
  app:
    image: transcription-app
    build:
      context: ./
      target: dev  # Change to 'production' for production builds
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3002:3002"
    environment:
      - GROQ_API_KEY=
      - GROQ_BASE_URL=https://api.groq.com/openai/v1  
      - NEXT_PUBLIC_SUPABASE_URL=
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=
